import z from "zod";
import { unixTimestampToDate } from "@/utils/date";
import { getPlayerRole, getVocationName } from "@/utils/player";

export const PlayerSchema = z.object({
	id: z.number(),
	name: z.string(),
	group_id: z.number().transform(getPlayerRole),
	account_id: z.number(),
	level: z.number(),
	vocation: z.number().transform(getVocationName),
	health: z.number(),
	healthmax: z.number(),
	experience: z.bigint(),
	lookbody: z.number(),
	lookfeet: z.number(),
	lookhead: z.number(),
	looklegs: z.number(),
	looktype: z.number(),
	lookaddons: z.number(),
	maglevel: z.number(),
	mana: z.number(),
	manamax: z.number(),
	manaspent: z.bigint(),
	soul: z.number(),
	town_id: z.number(),
	posx: z.number(),
	posy: z.number(),
	posz: z.number(),
	cap: z.number(),
	sex: z.number(),
	pronoun: z.number(),
	lastlogin: z.bigint().transform(unixTimestampToDate),
	lastip: z.number(),
	save: z.number(),
	skull: z.number(),
	skulltime: z.bigint(),
	lastlogout: z.bigint().transform(unixTimestampToDate),
	blessings: z.number(),
	blessings1: z.number(),
	blessings2: z.number(),
	blessings3: z.number(),
	blessings4: z.number(),
	blessings5: z.number(),
	blessings6: z.number(),
	blessings7: z.number(),
	blessings8: z.number(),
	onlinetime: z.number(), // in seconds
	deletion: z.bigint(),
	balance: z.bigint(),
	offlinetraining_time: z.number(), // is in seconds
	stamina: z.number(), // is in minutes
	skill_fist: z.number(),
	skill_fist_tries: z.bigint(),
	skill_club: z.number(),
	skill_club_tries: z.bigint(),
	skill_sword: z.number(),
	skill_sword_tries: z.bigint(),
	skill_axe: z.number(),
	skill_axe_tries: z.bigint(),
	skill_dist: z.number(),
	skill_dist_tries: z.bigint(),
	skill_shielding: z.number(),
	skill_shielding_tries: z.bigint(),
	skill_fishing: z.number(),
	skill_fishing_tries: z.bigint(),
	skill_critical_hit_chance: z.number(),
	skill_critical_hit_chance_tries: z.bigint(),
	skill_critical_hit_damage: z.number(),
	skill_critical_hit_damage_tries: z.bigint(),
	skill_life_leech_chance: z.number(),
	skill_life_leech_chance_tries: z.bigint(),
	skill_life_leech_amount: z.number(),
	skill_life_leech_amount_tries: z.bigint(),
	skill_mana_leech_chance: z.number(),
	skill_mana_leech_chance_tries: z.bigint(),
	skill_mana_leech_amount: z.number(),
	skill_mana_leech_amount_tries: z.bigint(),
	skill_criticalhit_chance: z.bigint(),
	skill_criticalhit_damage: z.bigint(),
	skill_lifeleech_chance: z.bigint(),
	skill_lifeleech_amount: z.bigint(),
	skill_manaleech_chance: z.bigint(),
	skill_manaleech_amount: z.bigint(),
	manashield: z.number(),
	max_manashield: z.number(),
	xpboost_stamina: z.number().nullable(), // is in seconds
	xpboost_value: z.number().nullable(), // how much percent
	marriage_status: z.bigint(),
	marriage_spouse: z.number(),
	bonus_rerolls: z.bigint(),
	prey_wildcard: z.bigint(),
	task_points: z.bigint(),
	quickloot_fallback: z.number(),
	lookmountbody: z.number(),
	lookmountfeet: z.number(),
	lookmounthead: z.number(),
	lookmountlegs: z.number(),
	currentmount: z.number(),
	lookfamiliarstype: z.number(),
	isreward: z.number(),
	istutorial: z.number(),
	forge_dusts: z.bigint(),
	forge_dust_level: z.bigint(),
	randomize_mount: z.number(),
	boss_points: z.number(),
	loyalty_points: z.number(),
	virtue: z.number(),
	harmony: z.number(),
});
