/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as Not_authRouteRouteImport } from './routes/_not_auth/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthAccountIndexRouteImport } from './routes/_auth/account/index'

const PublicTermsIndexLazyRouteImport = createFileRoute('/_public/terms/')()
const Not_authLoginIndexLazyRouteImport = createFileRoute('/_not_auth/login/')()
const AuthAccountDetailsIndexLazyRouteImport = createFileRoute(
  '/_auth/account/details/',
)()

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const Not_authRouteRoute = Not_authRouteRouteImport.update({
  id: '/_not_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTermsIndexLazyRoute = PublicTermsIndexLazyRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => PublicRouteRoute,
} as any).lazy(() =>
  import('./routes/_public/terms/index.lazy').then((d) => d.Route),
)
const Not_authLoginIndexLazyRoute = Not_authLoginIndexLazyRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => Not_authRouteRoute,
} as any).lazy(() =>
  import('./routes/_not_auth/login/index.lazy').then((d) => d.Route),
)
const AuthAccountIndexRoute = AuthAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/account/index.lazy').then((d) => d.Route),
)
const AuthAccountDetailsIndexLazyRoute =
  AuthAccountDetailsIndexLazyRouteImport.update({
    id: '/account/details/',
    path: '/account/details/',
    getParentRoute: () => AuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_auth/account/details/index.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/account': typeof AuthAccountIndexRoute
  '/login': typeof Not_authLoginIndexLazyRoute
  '/terms': typeof PublicTermsIndexLazyRoute
  '/account/details': typeof AuthAccountDetailsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/account': typeof AuthAccountIndexRoute
  '/login': typeof Not_authLoginIndexLazyRoute
  '/terms': typeof PublicTermsIndexLazyRoute
  '/account/details': typeof AuthAccountDetailsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_not_auth': typeof Not_authRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_auth/account/': typeof AuthAccountIndexRoute
  '/_not_auth/login/': typeof Not_authLoginIndexLazyRoute
  '/_public/terms/': typeof PublicTermsIndexLazyRoute
  '/_auth/account/details/': typeof AuthAccountDetailsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/login' | '/terms' | '/account/details'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/login' | '/terms' | '/account/details'
  id:
    | '__root__'
    | '/_auth'
    | '/_not_auth'
    | '/_public'
    | '/_public/'
    | '/_auth/account/'
    | '/_not_auth/login/'
    | '/_public/terms/'
    | '/_auth/account/details/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  Not_authRouteRoute: typeof Not_authRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_not_auth': {
      id: '/_not_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Not_authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terms/': {
      id: '/_public/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsIndexLazyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_not_auth/login/': {
      id: '/_not_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof Not_authLoginIndexLazyRouteImport
      parentRoute: typeof Not_authRouteRoute
    }
    '/_auth/account/': {
      id: '/_auth/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/account/details/': {
      id: '/_auth/account/details/'
      path: '/account/details'
      fullPath: '/account/details'
      preLoaderRoute: typeof AuthAccountDetailsIndexLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAccountIndexRoute: typeof AuthAccountIndexRoute
  AuthAccountDetailsIndexLazyRoute: typeof AuthAccountDetailsIndexLazyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAccountIndexRoute: AuthAccountIndexRoute,
  AuthAccountDetailsIndexLazyRoute: AuthAccountDetailsIndexLazyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface Not_authRouteRouteChildren {
  Not_authLoginIndexLazyRoute: typeof Not_authLoginIndexLazyRoute
}

const Not_authRouteRouteChildren: Not_authRouteRouteChildren = {
  Not_authLoginIndexLazyRoute: Not_authLoginIndexLazyRoute,
}

const Not_authRouteRouteWithChildren = Not_authRouteRoute._addFileChildren(
  Not_authRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicTermsIndexLazyRoute: typeof PublicTermsIndexLazyRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicTermsIndexLazyRoute: PublicTermsIndexLazyRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  Not_authRouteRoute: Not_authRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
