/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as Not_authRouteRouteImport } from './routes/_not_auth/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthAccountIndexRouteImport } from './routes/_auth/account/index'
import { Route as AuthAccountPlayerCreateIndexRouteImport } from './routes/_auth/account/player/create/index'
import { Route as AuthAccountPlayerNameUndeleteIndexRouteImport } from './routes/_auth/account/player/$name/undelete/index'
import { Route as AuthAccountPlayerNameEditIndexRouteImport } from './routes/_auth/account/player/$name/edit/index'
import { Route as AuthAccountPlayerNameDeleteIndexRouteImport } from './routes/_auth/account/player/$name/delete/index'

const PublicTermsIndexLazyRouteImport = createFileRoute('/_public/terms/')()
const Not_authLoginIndexLazyRouteImport = createFileRoute('/_not_auth/login/')()
const Not_authAccountCreateIndexLazyRouteImport = createFileRoute(
  '/_not_auth/account/create/',
)()
const AuthAccountRegistrationIndexLazyRouteImport = createFileRoute(
  '/_auth/account/registration/',
)()
const AuthAccountDetailsIndexLazyRouteImport = createFileRoute(
  '/_auth/account/details/',
)()
const AuthAccountCoins_historyIndexLazyRouteImport = createFileRoute(
  '/_auth/account/coins_history/',
)()
const AuthAccountAudit_historyIndexLazyRouteImport = createFileRoute(
  '/_auth/account/audit_history/',
)()

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const Not_authRouteRoute = Not_authRouteRouteImport.update({
  id: '/_not_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTermsIndexLazyRoute = PublicTermsIndexLazyRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => PublicRouteRoute,
} as any).lazy(() =>
  import('./routes/_public/terms/index.lazy').then((d) => d.Route),
)
const Not_authLoginIndexLazyRoute = Not_authLoginIndexLazyRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => Not_authRouteRoute,
} as any).lazy(() =>
  import('./routes/_not_auth/login/index.lazy').then((d) => d.Route),
)
const AuthAccountIndexRoute = AuthAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/account/index.lazy').then((d) => d.Route),
)
const Not_authAccountCreateIndexLazyRoute =
  Not_authAccountCreateIndexLazyRouteImport.update({
    id: '/account/create/',
    path: '/account/create/',
    getParentRoute: () => Not_authRouteRoute,
  } as any).lazy(() =>
    import('./routes/_not_auth/account/create/index.lazy').then((d) => d.Route),
  )
const AuthAccountRegistrationIndexLazyRoute =
  AuthAccountRegistrationIndexLazyRouteImport.update({
    id: '/account/registration/',
    path: '/account/registration/',
    getParentRoute: () => AuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_auth/account/registration/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthAccountDetailsIndexLazyRoute =
  AuthAccountDetailsIndexLazyRouteImport.update({
    id: '/account/details/',
    path: '/account/details/',
    getParentRoute: () => AuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_auth/account/details/index.lazy').then((d) => d.Route),
  )
const AuthAccountCoins_historyIndexLazyRoute =
  AuthAccountCoins_historyIndexLazyRouteImport.update({
    id: '/account/coins_history/',
    path: '/account/coins_history/',
    getParentRoute: () => AuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_auth/account/coins_history/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthAccountAudit_historyIndexLazyRoute =
  AuthAccountAudit_historyIndexLazyRouteImport.update({
    id: '/account/audit_history/',
    path: '/account/audit_history/',
    getParentRoute: () => AuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_auth/account/audit_history/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthAccountPlayerCreateIndexRoute =
  AuthAccountPlayerCreateIndexRouteImport.update({
    id: '/account/player/create/',
    path: '/account/player/create/',
    getParentRoute: () => AuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_auth/account/player/create/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthAccountPlayerNameUndeleteIndexRoute =
  AuthAccountPlayerNameUndeleteIndexRouteImport.update({
    id: '/account/player/$name/undelete/',
    path: '/account/player/$name/undelete/',
    getParentRoute: () => AuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_auth/account/player/$name/undelete/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthAccountPlayerNameEditIndexRoute =
  AuthAccountPlayerNameEditIndexRouteImport.update({
    id: '/account/player/$name/edit/',
    path: '/account/player/$name/edit/',
    getParentRoute: () => AuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_auth/account/player/$name/edit/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthAccountPlayerNameDeleteIndexRoute =
  AuthAccountPlayerNameDeleteIndexRouteImport.update({
    id: '/account/player/$name/delete/',
    path: '/account/player/$name/delete/',
    getParentRoute: () => AuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_auth/account/player/$name/delete/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/account': typeof AuthAccountIndexRoute
  '/login': typeof Not_authLoginIndexLazyRoute
  '/terms': typeof PublicTermsIndexLazyRoute
  '/account/audit_history': typeof AuthAccountAudit_historyIndexLazyRoute
  '/account/coins_history': typeof AuthAccountCoins_historyIndexLazyRoute
  '/account/details': typeof AuthAccountDetailsIndexLazyRoute
  '/account/registration': typeof AuthAccountRegistrationIndexLazyRoute
  '/account/create': typeof Not_authAccountCreateIndexLazyRoute
  '/account/player/create': typeof AuthAccountPlayerCreateIndexRoute
  '/account/player/$name/delete': typeof AuthAccountPlayerNameDeleteIndexRoute
  '/account/player/$name/edit': typeof AuthAccountPlayerNameEditIndexRoute
  '/account/player/$name/undelete': typeof AuthAccountPlayerNameUndeleteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/account': typeof AuthAccountIndexRoute
  '/login': typeof Not_authLoginIndexLazyRoute
  '/terms': typeof PublicTermsIndexLazyRoute
  '/account/audit_history': typeof AuthAccountAudit_historyIndexLazyRoute
  '/account/coins_history': typeof AuthAccountCoins_historyIndexLazyRoute
  '/account/details': typeof AuthAccountDetailsIndexLazyRoute
  '/account/registration': typeof AuthAccountRegistrationIndexLazyRoute
  '/account/create': typeof Not_authAccountCreateIndexLazyRoute
  '/account/player/create': typeof AuthAccountPlayerCreateIndexRoute
  '/account/player/$name/delete': typeof AuthAccountPlayerNameDeleteIndexRoute
  '/account/player/$name/edit': typeof AuthAccountPlayerNameEditIndexRoute
  '/account/player/$name/undelete': typeof AuthAccountPlayerNameUndeleteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_not_auth': typeof Not_authRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_auth/account/': typeof AuthAccountIndexRoute
  '/_not_auth/login/': typeof Not_authLoginIndexLazyRoute
  '/_public/terms/': typeof PublicTermsIndexLazyRoute
  '/_auth/account/audit_history/': typeof AuthAccountAudit_historyIndexLazyRoute
  '/_auth/account/coins_history/': typeof AuthAccountCoins_historyIndexLazyRoute
  '/_auth/account/details/': typeof AuthAccountDetailsIndexLazyRoute
  '/_auth/account/registration/': typeof AuthAccountRegistrationIndexLazyRoute
  '/_not_auth/account/create/': typeof Not_authAccountCreateIndexLazyRoute
  '/_auth/account/player/create/': typeof AuthAccountPlayerCreateIndexRoute
  '/_auth/account/player/$name/delete/': typeof AuthAccountPlayerNameDeleteIndexRoute
  '/_auth/account/player/$name/edit/': typeof AuthAccountPlayerNameEditIndexRoute
  '/_auth/account/player/$name/undelete/': typeof AuthAccountPlayerNameUndeleteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/terms'
    | '/account/audit_history'
    | '/account/coins_history'
    | '/account/details'
    | '/account/registration'
    | '/account/create'
    | '/account/player/create'
    | '/account/player/$name/delete'
    | '/account/player/$name/edit'
    | '/account/player/$name/undelete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/terms'
    | '/account/audit_history'
    | '/account/coins_history'
    | '/account/details'
    | '/account/registration'
    | '/account/create'
    | '/account/player/create'
    | '/account/player/$name/delete'
    | '/account/player/$name/edit'
    | '/account/player/$name/undelete'
  id:
    | '__root__'
    | '/_auth'
    | '/_not_auth'
    | '/_public'
    | '/_public/'
    | '/_auth/account/'
    | '/_not_auth/login/'
    | '/_public/terms/'
    | '/_auth/account/audit_history/'
    | '/_auth/account/coins_history/'
    | '/_auth/account/details/'
    | '/_auth/account/registration/'
    | '/_not_auth/account/create/'
    | '/_auth/account/player/create/'
    | '/_auth/account/player/$name/delete/'
    | '/_auth/account/player/$name/edit/'
    | '/_auth/account/player/$name/undelete/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  Not_authRouteRoute: typeof Not_authRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_not_auth': {
      id: '/_not_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Not_authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terms/': {
      id: '/_public/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsIndexLazyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_not_auth/login/': {
      id: '/_not_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof Not_authLoginIndexLazyRouteImport
      parentRoute: typeof Not_authRouteRoute
    }
    '/_auth/account/': {
      id: '/_auth/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_not_auth/account/create/': {
      id: '/_not_auth/account/create/'
      path: '/account/create'
      fullPath: '/account/create'
      preLoaderRoute: typeof Not_authAccountCreateIndexLazyRouteImport
      parentRoute: typeof Not_authRouteRoute
    }
    '/_auth/account/registration/': {
      id: '/_auth/account/registration/'
      path: '/account/registration'
      fullPath: '/account/registration'
      preLoaderRoute: typeof AuthAccountRegistrationIndexLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/account/details/': {
      id: '/_auth/account/details/'
      path: '/account/details'
      fullPath: '/account/details'
      preLoaderRoute: typeof AuthAccountDetailsIndexLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/account/coins_history/': {
      id: '/_auth/account/coins_history/'
      path: '/account/coins_history'
      fullPath: '/account/coins_history'
      preLoaderRoute: typeof AuthAccountCoins_historyIndexLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/account/audit_history/': {
      id: '/_auth/account/audit_history/'
      path: '/account/audit_history'
      fullPath: '/account/audit_history'
      preLoaderRoute: typeof AuthAccountAudit_historyIndexLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/account/player/create/': {
      id: '/_auth/account/player/create/'
      path: '/account/player/create'
      fullPath: '/account/player/create'
      preLoaderRoute: typeof AuthAccountPlayerCreateIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/account/player/$name/undelete/': {
      id: '/_auth/account/player/$name/undelete/'
      path: '/account/player/$name/undelete'
      fullPath: '/account/player/$name/undelete'
      preLoaderRoute: typeof AuthAccountPlayerNameUndeleteIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/account/player/$name/edit/': {
      id: '/_auth/account/player/$name/edit/'
      path: '/account/player/$name/edit'
      fullPath: '/account/player/$name/edit'
      preLoaderRoute: typeof AuthAccountPlayerNameEditIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/account/player/$name/delete/': {
      id: '/_auth/account/player/$name/delete/'
      path: '/account/player/$name/delete'
      fullPath: '/account/player/$name/delete'
      preLoaderRoute: typeof AuthAccountPlayerNameDeleteIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAccountIndexRoute: typeof AuthAccountIndexRoute
  AuthAccountAudit_historyIndexLazyRoute: typeof AuthAccountAudit_historyIndexLazyRoute
  AuthAccountCoins_historyIndexLazyRoute: typeof AuthAccountCoins_historyIndexLazyRoute
  AuthAccountDetailsIndexLazyRoute: typeof AuthAccountDetailsIndexLazyRoute
  AuthAccountRegistrationIndexLazyRoute: typeof AuthAccountRegistrationIndexLazyRoute
  AuthAccountPlayerCreateIndexRoute: typeof AuthAccountPlayerCreateIndexRoute
  AuthAccountPlayerNameDeleteIndexRoute: typeof AuthAccountPlayerNameDeleteIndexRoute
  AuthAccountPlayerNameEditIndexRoute: typeof AuthAccountPlayerNameEditIndexRoute
  AuthAccountPlayerNameUndeleteIndexRoute: typeof AuthAccountPlayerNameUndeleteIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAccountIndexRoute: AuthAccountIndexRoute,
  AuthAccountAudit_historyIndexLazyRoute:
    AuthAccountAudit_historyIndexLazyRoute,
  AuthAccountCoins_historyIndexLazyRoute:
    AuthAccountCoins_historyIndexLazyRoute,
  AuthAccountDetailsIndexLazyRoute: AuthAccountDetailsIndexLazyRoute,
  AuthAccountRegistrationIndexLazyRoute: AuthAccountRegistrationIndexLazyRoute,
  AuthAccountPlayerCreateIndexRoute: AuthAccountPlayerCreateIndexRoute,
  AuthAccountPlayerNameDeleteIndexRoute: AuthAccountPlayerNameDeleteIndexRoute,
  AuthAccountPlayerNameEditIndexRoute: AuthAccountPlayerNameEditIndexRoute,
  AuthAccountPlayerNameUndeleteIndexRoute:
    AuthAccountPlayerNameUndeleteIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface Not_authRouteRouteChildren {
  Not_authLoginIndexLazyRoute: typeof Not_authLoginIndexLazyRoute
  Not_authAccountCreateIndexLazyRoute: typeof Not_authAccountCreateIndexLazyRoute
}

const Not_authRouteRouteChildren: Not_authRouteRouteChildren = {
  Not_authLoginIndexLazyRoute: Not_authLoginIndexLazyRoute,
  Not_authAccountCreateIndexLazyRoute: Not_authAccountCreateIndexLazyRoute,
}

const Not_authRouteRouteWithChildren = Not_authRouteRoute._addFileChildren(
  Not_authRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicTermsIndexLazyRoute: typeof PublicTermsIndexLazyRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicTermsIndexLazyRoute: PublicTermsIndexLazyRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  Not_authRouteRoute: Not_authRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
